# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: OpenADT.OpenADT
PackageVersion: 1.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: openadt-1.0.0/openadt.exe
    PortableCommandAlias: openadt
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/abapify/openadt/releases/download/v1.0.0/openadt-1.0.0.zip
    InstallerSha256: FB17263A1FEDAC52E74FBF4A5959BEB5DC7818D5B5791CBEF6D73FB0F5EF20F6
Commands:
  - openadt
Dependencies:
  PackageDependencies:
    - PackageIdentifier: EclipseAdoptium.Temurin.21.JDK
ReleaseDate: 2026-05-22
ManifestType: installer
ManifestVersion: 1.9.0
