# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: OpenADT.OpenADT
PackageVersion: 1.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: openadt-1.1.0/openadt.exe
    PortableCommandAlias: openadt
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/abapify/openadt/releases/download/v1.1.0/openadt-1.1.0.zip
    InstallerSha256: B38D5AE6DAC1FC48259F6A2DBCA4471A730308B56559B2A867637C4C983313F5
Commands:
  - openadt
Dependencies:
  PackageDependencies:
    - PackageIdentifier: EclipseAdoptium.Temurin.21.JDK
ReleaseDate: 2026-05-24
ManifestType: installer
ManifestVersion: 1.9.0
