# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: OpenADT.OpenADT
PackageVersion: 1.2.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: openadt-1.2.4/openadt.exe
    PortableCommandAlias: openadt
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/abapify/openadt/releases/download/v1.2.4/openadt-1.2.4.zip
    InstallerSha256: C3B3D6E614BD11D606445EC4DA17B59845E3490362B5F80DCE6E912249127BA3
Commands:
  - openadt
Dependencies:
  PackageDependencies:
    - PackageIdentifier: EclipseAdoptium.Temurin.21.JDK
ReleaseDate: 2026-06-01
ManifestType: installer
ManifestVersion: 1.9.0
