# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: OpenADT.OpenADT
PackageVersion: 1.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: openadt-1.2.1/openadt.exe
    PortableCommandAlias: openadt
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/abapify/openadt/releases/download/v1.2.1/openadt-1.2.1.zip
    InstallerSha256: 843B73A5B2A173B2894A96BFB682C1E629BA32A5E8673DB977D0CF06FA5F1B9B
Commands:
  - openadt
Dependencies:
  PackageDependencies:
    - PackageIdentifier: EclipseAdoptium.Temurin.21.JDK
ReleaseDate: 2026-06-01
ManifestType: installer
ManifestVersion: 1.9.0
